import type { Metadata } from "next";
import "./globals.css";
import { WishlistProvider } from "./context/wishList-Context";
import { ClerkProvider,  SignedOut, } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
          <body>
          <ClerkProvider >
            <SignedOut>
            </SignedOut>
            <WishlistProvider>
            {children}
            </WishlistProvider>
      </ClerkProvider>
          </body>
        </html>
  );
}